Updated Using Typescript
There were some major changes that took place for node, express and typescript to play nice together.
Here is a short guide

*** Using Node.js and Typescript ***

1. To globally install the latest stable build of Typescript :
type in command line-> npm install -g typescript

2. Make a project directory.

3. Move into the new directory.

4. Create a tsconfig.json file.
type in command line -> tsc --init

5. Edit tsconfig.json to build js file using tsc.  Replace contents of current file with contents below.
This gets tsc to compile using ES6 syntax.  Also targets current ts file so the tsconfig file will be seen.
{
  "compilerOptions": {
    /* Basic Options */
    "target": "ES2016",               /* Specify ECMAScript target version: 'ES3'(default), 'ES5', 'ES2015', 'ES2016', 'ES2017','ES2018' or 'ESNEXT'. */
    "module": "commonjs",             /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */
    "lib": [
      "DOM",
      "ES2016"
    ],
    "strict": true,                   /* Enable all strict type-checking options. */
    "strictNullChecks": false,        /* Enable strict null checks. */
    "esModuleInterop": true           /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */
  },
  "files":[
    "<filename>.ts"                         /* place name of ts file you are building here */
  ]
}

6. Create a package.json file
Type in command line -> npm init

7. Install @types/node module
Type in command line -> npm install @types/node --save-dev
This allows the use of require statements in typescript else you would get this error:
test.ts(8,13): error TS2304: Cannot find name 'require'.

8. Install @types/express module
Type in command line -> npm install @types/express --save-dev
This allows the use of express functions

9. Install npm package as normal
Type in command line -> npm install <packagename> --save

10. Write ts file using node modules as normal.

11. Then compile:
Type in command line -> tsc
There should be no errors concerning the require statements

12. Run js file using Node.js
Type in command line -> node <filename>.js
File should run fine.